version: '3.9'
services:
  php-apache-env:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: always
    ports:
      - ${APACHE_PORT}:80
    volumes:
      - /Users/safesploit/Documents/GitHub/doogle:/var/www/html:ro
    depends_on:
      - mysql_db

  mysql_db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

# # Included for debugging
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql_db
    depends_on:
      - mysql_db
